languageCode = "fr"
languageName = "French"
weight = 1

title = "Idées de projets étudiants — HE-Arc Ingénierie"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  logo = "arc_square_logo.png"
  description = "Catalogue des idées de projets de semestre (P1/P2/P3), de travaux de Bachelor et de Ra&D proposées aux étudiants de la HE-Arc Ingénierie."
  dateFormat = "2006"

[params.author]
  name = "Haute École Arc Ingénierie"
  image = "arc_ing_logo.png"
  headline = "Haute École Arc Ingénierie"
  bio = "La Haute École Arc Ingénierie est au service d'une industrie unique au monde. Nous formons les ingénieurs dont celle-ci a besoin pour se maintenir à la pointe de l'innovation et l'accompagnons dans ses activités de recherche appliquée et développement."
